<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * Nama tabel di database.
     */
    protected $table = 'users';

    /**
     * Primary key kustom.
     */
    protected $primaryKey = 'id_user';

    /**
     * Tipe primary key.
     */
    protected $keyType = 'int';

    /**
     * Auto increment tetap true karena BIGINT GENERATED BY DEFAULT AS IDENTITY.
     */
    public $incrementing = true;

    /**
     * Supabase menggunakan created_at saja, tanpa updated_at.
     */
    public $timestamps = false;

    /**
     * Kolom yang boleh diisi massal.
     */
    protected $fillable = [
        'nama_lengkap',
        'email',
        'password',
        'nomor_telepon',
        'alamat_kost',
    ];

    /**
     * Kolom yang disembunyikan dari serialisasi.
     */
    protected $hidden = [
        'password',
    ];

    /**
     * Cast tipe data.
     */
    protected function casts(): array
    {
        return [
            'password'   => 'hashed',
            'created_at' => 'datetime',
        ];
    }
}
